#!/usr/bin/env bash

# Author: Brian Deane
# whattime
# A command that takes a time for a given location to display times in other timezones.

# getopt example stolen from
# http://bahmanm.com/blogs/command-line-options-how-to-parse-in-bash-using-getopt

# exit statuses:
# 1 - provided illegal arguments
# 3 - provided duplicate arguments
# 4 - provided too few arguments
# 5 - display timezone not found in /usr/share/zoneinfo/
# as always, please see the specific error message

# --now
# --when
# --here
# --in
# --display

# pipelines don't automatically fail if a component fails
# needed for find | head -n1 calls that don't find anything
set +o pipefail
set -o errexit

echo_error() {
  echo "$1" 1>&2
}

find_tz() {
  find /usr/share/zoneinfo/ -iname $(basename $1) -or -ipath "$(basename $1)" | head -n1
}

TEMP=`getopt -o i:nhw:d: --long in:,now,here,when:,display: -n "$0" -- "$@"`
eval set -- "$TEMP"
unset TEMP

while true ; do
  case "$1" in
    -i|--in)
      [ -n "$IN" ] && echo_error "cannot use --in more than once" && exit 3
      IN="$2"
      shift 2
      ;;
    -n|--now) NOW="now" ; shift ;;
    -h|--here) HERE="here" ; shift ;;
    -w|--when)
      [ -n "$TIME" ] && echo_error "cannot use --when more than once" && exit 3
      TIME=$2
      shift 2
      ;;
    -d|--display)
      if [ -z "$DISPLAYS" ]; then
        DISPLAYS="$2"
      else
        DISPLAYS="$DISPLAYS,$2"
      fi
      shift 2
      ;;
    --) shift ; break ;;
    *) echo_error "stop providing garbage arguments ($1)" ; exit 1 ;;
  esac
done

if [ -n "$HERE" ]; then
  if [ -z "$IN" ]; then
    IN="$(head -n1 /etc/timezone)"
  else
    echo_error "cannot use --here / --in more than once"
    exit 3
  fi
fi

if [ -n "$NOW" ]; then
  if [ -z "$TIME" ]; then
    TIME="$(date --date "TZ=\"$IN\" $(date +"%b %e %T")")"
  else
    echo_error "cannot use --now / --when more than once"
    exit 3
  fi
fi

[ -z "$TIME" ] && echo_error "must provide either --when <datetime> or --now" && exit 4
[ -z "$IN" ] && echo_error "must provide either --in <timezone> or --here" && exit 4
[ -z "$DISPLAYS" ] && echo_error "must provide --display" && exit 4

TIMEZONES=""
for display in $(echo $DISPLAYS | tr ',' '\n'); do
  timezone="$(find_tz "$display")"
  if [ -z "$timezone" ]; then
    echo_error "timezone info for \"$display\" not found."
    exit 4
  else
    TIMEZONES="$TIMEZONES,$timezone"
  fi
done

for timezone in $(echo $TIMEZONES | tr ',' '\n'); do
  in="$(find_tz "$IN")"
  if [ -z "$in" ]; then
    echo_error "timezone info for \"$in\" not found."
    exit 4
  fi

  echo -n "What time is it in $(basename $timezone) when it is $TIME in $(basename $in)?: "
  TZ=$timezone date --date "TZ=\"$in\" $TIME" +'%b %e %T %Z'
done
